baseURL = "https://comm2100.kristenjz.com/"
languageCode = "en-us"
title = "COMM 2100 with Kristen"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    footer = "Built with [<u>Hugo</u>](https://gohugo.io/). Framework copied from [Hongtao Hao's <u>personal website</u>.](https://github.com/hongtaoh/c101)<br />Content in [<u>GitHub Repo</u>.](https://github.com/KristenJZ/comm2100)"


[[menu.main]]
    name = "Policy"
    url = "/policy/"
    weight = 1
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 2
[[menu.main]]
    name = "Notes on Class"
    url = "/notes/"
    weight = 3


[markup]
   defaultMarkdownHandler = "goldmark"
   [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      strikethrough = true
      table = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      
[markup.tableOfContents]
  endLevel = 2
  ordered = true
  startLevel = 1